// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"
#include "behaviac_customized_types.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }

	inline void Set_CCmptMonsterAI_m_eCurState(Agent* self, AIState value) { ((CCmptMonsterAI*)self)->m_eCurState = value; };
	inline const void* Get_CCmptMonsterAI_m_eCurState(Agent* self) { return &((CCmptMonsterAI*)self)->m_eCurState; };

	inline void Set_CCmptMonsterAI_m_ullRestExpire(Agent* self, unsigned long long value) { ((CCmptMonsterAI*)self)->m_ullRestExpire = value; };
	inline const void* Get_CCmptMonsterAI_m_ullRestExpire(Agent* self) { return &((CCmptMonsterAI*)self)->m_ullRestExpire; };

	inline void FunctionPointer_CCmptMonsterAI_LogMessage(char* param0) { CCmptMonsterAI::LogMessage(param0); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
