# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner/teamsvr.proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import innercommon_pb2 as innercommon__pb2
import fight3v3common_pb2 as fight3v3common__pb2
import fight5v5common_pb2 as fight5v5common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19inner/teamsvr.proto.proto\x12\x05inner\x1a\x0c\x63ommon.proto\x1a\x11innercommon.proto\x1a\x14\x66ight3v3common.proto\x1a\x14\x66ight5v5common.proto\"\x9a\x02\n\x0cInnerTeamsvr\x12\x10\n\x08\x66romuser\x18\x01 \x01(\x04\x12\x10\n\x08\x66romzone\x18\x02 \x01(\r\x12=\n\x0e\x66romscene_test\x18\xf9\n \x01(\x0b\x32\".inner.InnerTeamsvr_Fromscene_TestH\x00\x12G\n\x13\x66romscene_gameevent\x18\xfa\n \x01(\x0b\x32\'.inner.InnerTeamsvr_Fromscene_GameEventH\x00\x12Q\n\x18\x66romscene_updateuserinfo\x18\xfb\n \x01(\x0b\x32,.inner.InnerTeamsvr_Fromscene_UpdateUserInfoH\x00\x42\x0b\n\tFromscene\"\x1d\n\x1bInnerTeamsvr_Fromscene_Test\"M\n InnerTeamsvr_Fromscene_GameEvent\x12)\n\noGameEvent\x18\x01 \x01(\x0b\x32\x15.inner.InnerGameEvent\"\xd0\x02\n%InnerTeamsvr_Fromscene_UpdateUserInfo\x12$\n\x05\x65xtd2\x18\x01 \x01(\x0b\x32\x13.common.RoleExtend2H\x00\x12$\n\x05\x65xtd3\x18\x02 \x01(\x0b\x32\x13.common.RoleExtend3H\x00\x12\x12\n\x08nickName\x18\x03 \x01(\tH\x00\x12\x12\n\x08headIcon\x18\x04 \x01(\rH\x00\x12\x13\n\theadFrame\x18\x05 \x01(\rH\x00\x12\x12\n\x08\x63\x61reerId\x18\x06 \x01(\rH\x00\x12\x0f\n\x05level\x18\x07 \x01(\rH\x00\x12\r\n\x03sex\x18\x08 \x01(\rH\x00\x12\x14\n\ncareeLevel\x18\t \x01(\rH\x00\x12%\n\x03\x66\x33\x33\x18\n \x01(\x0b\x32\x16.common.ExtendFight3v3H\x00\x12%\n\x03\x66\x35\x35\x18\x0b \x01(\x0b\x32\x16.common.ExtendFight5v5H\x00\x42\x06\n\x04typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inner.teamsvr.proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INNERTEAMSVR._serialized_start=114
  _INNERTEAMSVR._serialized_end=396
  _INNERTEAMSVR_FROMSCENE_TEST._serialized_start=398
  _INNERTEAMSVR_FROMSCENE_TEST._serialized_end=427
  _INNERTEAMSVR_FROMSCENE_GAMEEVENT._serialized_start=429
  _INNERTEAMSVR_FROMSCENE_GAMEEVENT._serialized_end=506
  _INNERTEAMSVR_FROMSCENE_UPDATEUSERINFO._serialized_start=509
  _INNERTEAMSVR_FROMSCENE_UPDATEUSERINFO._serialized_end=845
# @@protoc_insertion_point(module_scope)
