# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63lient/common.proto\x12\x06\x63ommon\"\xb4\x01\n\tRoleBrief\x12\x10\n\x08llRoleId\x18\x01 \x01(\x04\x12\x0f\n\x07strNick\x18\x02 \x01(\x0c\x12\x12\n\nuiHeadIcon\x18\x03 \x01(\r\x12\x13\n\x0buiHeadFrame\x18\x04 \x01(\r\x12\x12\n\nuiCareerId\x18\x05 \x01(\r\x12\x0f\n\x07uiLevel\x18\x06 \x01(\r\x12\r\n\x05uiSex\x18\x07 \x01(\r\x12\x15\n\ruiCareerLevel\x18\x08 \x01(\r\x12\x10\n\x08uiZonIdF\x18\t \x01(\r\"C\n\rClientSceneId\x12\r\n\x05mapId\x18\x01 \x01(\r\x12\x10\n\x08procType\x18\x02 \x01(\r\x12\x11\n\tprocParam\x18\x03 \x01(\r\"#\n\x11\x43lientStaticScene\x12\x0e\n\x06lineId\x18\x01 \x01(\r\"3\n\x0f\x43lientCopyScene\x12\x10\n\x08\x63opyLvId\x18\x01 \x01(\r\x12\x0e\n\x06\x61utoId\x18\x02 \x01(\r\"I\n\tClientPos\x12\x0c\n\x04poxX\x18\x01 \x01(\r\x12\x0c\n\x04posY\x18\x02 \x01(\r\x12\x0f\n\x07offsetX\x18\x03 \x01(\r\x12\x0f\n\x07offsetY\x18\x04 \x01(\r\"B\n\x0f\x43lientPosDirect\x12\x1f\n\x04\x63pos\x18\x01 \x01(\x0b\x32\x11.common.ClientPos\x12\x0e\n\x06\x64irect\x18\x02 \x01(\r\"L\n\x12\x43lientPosTerminate\x12\x12\n\nservertime\x18\x01 \x01(\x04\x12\"\n\x07posList\x18\x02 \x03(\x0b\x32\x11.common.ClientPos\"V\n\x0bRoleExtend2\x12&\n\x07sceneId\x18\x01 \x01(\x0b\x32\x15.common.ClientSceneId\x12\x1f\n\x04\x63pos\x18\x02 \x01(\x0b\x32\x11.common.ClientPos\"C\n\x0bRoleExtend3\x12\n\n\x02hp\x18\x01 \x01(\r\x12\r\n\x05maxHp\x18\x02 \x01(\r\x12\n\n\x02mp\x18\x03 \x01(\r\x12\r\n\x05maxMp\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLEBRIEF._serialized_start=32
  _ROLEBRIEF._serialized_end=212
  _CLIENTSCENEID._serialized_start=214
  _CLIENTSCENEID._serialized_end=281
  _CLIENTSTATICSCENE._serialized_start=283
  _CLIENTSTATICSCENE._serialized_end=318
  _CLIENTCOPYSCENE._serialized_start=320
  _CLIENTCOPYSCENE._serialized_end=371
  _CLIENTPOS._serialized_start=373
  _CLIENTPOS._serialized_end=446
  _CLIENTPOSDIRECT._serialized_start=448
  _CLIENTPOSDIRECT._serialized_end=514
  _CLIENTPOSTERMINATE._serialized_start=516
  _CLIENTPOSTERMINATE._serialized_end=592
  _ROLEEXTEND2._serialized_start=594
  _ROLEEXTEND2._serialized_end=680
  _ROLEEXTEND3._serialized_start=682
  _ROLEEXTEND3._serialized_end=749
# @@protoc_insertion_point(module_scope)
