# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/itemcommon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63lient/itemcommon.proto\x12\x06\x63ommon\"\xaa\x01\n\x08ItemBase\x12\r\n\x05uiUid\x18\x01 \x01(\r\x12\r\n\x05uiTid\x18\x02 \x01(\r\x12\x0f\n\x07uiCount\x18\x03 \x01(\r\x12\x0e\n\x06uiBind\x18\x04 \x01(\r\x12\x10\n\x08uiExpire\x18\x05 \x01(\r\x12\x11\n\tuiQuality\x18\x06 \x01(\r\x12\x15\n\ruiTradeExpire\x18\x07 \x01(\r\x12\x0f\n\x07uiPrice\x18\x08 \x01(\r\x12\x12\n\nbNotSorted\x18\t \x01(\x08\"\'\n\x04Item\x12\x1f\n\x05oBase\x18\x01 \x01(\x0b\x32\x10.common.ItemBaseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.itemcommon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMBASE._serialized_start=36
  _ITEMBASE._serialized_end=206
  _ITEM._serialized_start=208
  _ITEM._serialized_end=247
# @@protoc_insertion_point(module_scope)
