# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record/record.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import recordfriend_pb2 as recordfriend__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13record/record.proto\x12\x06record\x1a\x12recordfriend.proto\"\x8e\x01\n\x0fRecordModuleAll\x12\x35\n\x07modules\x18\x01 \x03(\x0b\x32$.record.RecordModuleAll.ModulesEntry\x1a\x44\n\x0cModulesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.record.RecordModule:\x02\x38\x01\"N\n\x0cRecordModule\x12\x33\n\roRecordFriend\x18\x01 \x01(\x0b\x32\x1a.record.RecordModuleFriendH\x00\x42\t\n\x07oModuleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record.record_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORDMODULEALL_MODULESENTRY._options = None
  _RECORDMODULEALL_MODULESENTRY._serialized_options = b'8\001'
  _RECORDMODULEALL._serialized_start=52
  _RECORDMODULEALL._serialized_end=194
  _RECORDMODULEALL_MODULESENTRY._serialized_start=126
  _RECORDMODULEALL_MODULESENTRY._serialized_end=194
  _RECORDMODULE._serialized_start=196
  _RECORDMODULE._serialized_end=274
# @@protoc_insertion_point(module_scope)
