// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_auction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_auction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include "auctioncommon.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_auction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_auction_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_auction_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace client {

enum enModuleAuction : int {
  enModuleAuction_None = 0,
  enModuleAuction_GoodsUp_Req = 1,
  enModuleAuction_GoodsUp_Ntf = 2,
  enModuleAuction_RealMax = 21,
  enModuleAuction_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  enModuleAuction_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool enModuleAuction_IsValid(int value);
constexpr enModuleAuction enModuleAuction_MIN = enModuleAuction_None;
constexpr enModuleAuction enModuleAuction_MAX = enModuleAuction_RealMax;
constexpr int enModuleAuction_ARRAYSIZE = enModuleAuction_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* enModuleAuction_descriptor();
template<typename T>
inline const std::string& enModuleAuction_Name(T enum_t_value) {
  static_assert(::std::is_same<T, enModuleAuction>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function enModuleAuction_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    enModuleAuction_descriptor(), enum_t_value);
}
inline bool enModuleAuction_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, enModuleAuction* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<enModuleAuction>(
    enModuleAuction_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace client

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::client::enModuleAuction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::client::enModuleAuction>() {
  return ::client::enModuleAuction_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_auction_2eproto
