// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: familysvr.proto

#include "familysvr.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace inner {
PROTOBUF_CONSTEXPR InnerFamilysvr::InnerFamilysvr(
    ::_pbi::ConstantInitialized)
  : fromuser_(uint64_t{0u})
  , _oneof_case_{}{}
struct InnerFamilysvrDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerFamilysvrDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerFamilysvrDefaultTypeInternal() {}
  union {
    InnerFamilysvr _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerFamilysvrDefaultTypeInternal _InnerFamilysvr_default_instance_;
PROTOBUF_CONSTEXPR InnerFamilysvr_Fromscene_Test::InnerFamilysvr_Fromscene_Test(
    ::_pbi::ConstantInitialized){}
struct InnerFamilysvr_Fromscene_TestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerFamilysvr_Fromscene_TestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerFamilysvr_Fromscene_TestDefaultTypeInternal() {}
  union {
    InnerFamilysvr_Fromscene_Test _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerFamilysvr_Fromscene_TestDefaultTypeInternal _InnerFamilysvr_Fromscene_Test_default_instance_;
}  // namespace inner
static ::_pb::Metadata file_level_metadata_familysvr_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_familysvr_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_familysvr_2eproto = nullptr;

const uint32_t TableStruct_familysvr_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerFamilysvr, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::inner::InnerFamilysvr, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inner::InnerFamilysvr, fromuser_),
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::inner::InnerFamilysvr, Fromscene_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerFamilysvr_Fromscene_Test, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::inner::InnerFamilysvr)},
  { 9, -1, -1, sizeof(::inner::InnerFamilysvr_Fromscene_Test)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::inner::_InnerFamilysvr_default_instance_._instance,
  &::inner::_InnerFamilysvr_Fromscene_Test_default_instance_._instance,
};

const char descriptor_table_protodef_familysvr_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017familysvr.proto\022\005inner\"o\n\016InnerFamilys"
  "vr\022\020\n\010fromuser\030\001 \001(\004\022>\n\016fromscene_test\030e"
  " \001(\0132$.inner.InnerFamilysvr_Fromscene_Te"
  "stH\000B\013\n\tFromscene\"\037\n\035InnerFamilysvr_From"
  "scene_Testb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_familysvr_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_familysvr_2eproto = {
    false, false, 178, descriptor_table_protodef_familysvr_2eproto,
    "familysvr.proto",
    &descriptor_table_familysvr_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_familysvr_2eproto::offsets,
    file_level_metadata_familysvr_2eproto, file_level_enum_descriptors_familysvr_2eproto,
    file_level_service_descriptors_familysvr_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_familysvr_2eproto_getter() {
  return &descriptor_table_familysvr_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_familysvr_2eproto(&descriptor_table_familysvr_2eproto);
namespace inner {

// ===================================================================

class InnerFamilysvr::_Internal {
 public:
  static const ::inner::InnerFamilysvr_Fromscene_Test& fromscene_test(const InnerFamilysvr* msg);
};

const ::inner::InnerFamilysvr_Fromscene_Test&
InnerFamilysvr::_Internal::fromscene_test(const InnerFamilysvr* msg) {
  return *msg->Fromscene_.fromscene_test_;
}
void InnerFamilysvr::set_allocated_fromscene_test(::inner::InnerFamilysvr_Fromscene_Test* fromscene_test) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Fromscene();
  if (fromscene_test) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(fromscene_test);
    if (message_arena != submessage_arena) {
      fromscene_test = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fromscene_test, submessage_arena);
    }
    set_has_fromscene_test();
    Fromscene_.fromscene_test_ = fromscene_test;
  }
  // @@protoc_insertion_point(field_set_allocated:inner.InnerFamilysvr.fromscene_test)
}
InnerFamilysvr::InnerFamilysvr(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:inner.InnerFamilysvr)
}
InnerFamilysvr::InnerFamilysvr(const InnerFamilysvr& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  fromuser_ = from.fromuser_;
  clear_has_Fromscene();
  switch (from.Fromscene_case()) {
    case kFromsceneTest: {
      _internal_mutable_fromscene_test()->::inner::InnerFamilysvr_Fromscene_Test::MergeFrom(from._internal_fromscene_test());
      break;
    }
    case FROMSCENE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:inner.InnerFamilysvr)
}

inline void InnerFamilysvr::SharedCtor() {
fromuser_ = uint64_t{0u};
clear_has_Fromscene();
}

InnerFamilysvr::~InnerFamilysvr() {
  // @@protoc_insertion_point(destructor:inner.InnerFamilysvr)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InnerFamilysvr::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_Fromscene()) {
    clear_Fromscene();
  }
}

void InnerFamilysvr::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerFamilysvr::clear_Fromscene() {
// @@protoc_insertion_point(one_of_clear_start:inner.InnerFamilysvr)
  switch (Fromscene_case()) {
    case kFromsceneTest: {
      if (GetArenaForAllocation() == nullptr) {
        delete Fromscene_.fromscene_test_;
      }
      break;
    }
    case FROMSCENE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = FROMSCENE_NOT_SET;
}


void InnerFamilysvr::Clear() {
// @@protoc_insertion_point(message_clear_start:inner.InnerFamilysvr)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fromuser_ = uint64_t{0u};
  clear_Fromscene();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerFamilysvr::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 fromuser = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          fromuser_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .inner.InnerFamilysvr_Fromscene_Test fromscene_test = 101;
      case 101:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_fromscene_test(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerFamilysvr::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inner.InnerFamilysvr)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 fromuser = 1;
  if (this->_internal_fromuser() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_fromuser(), target);
  }

  // .inner.InnerFamilysvr_Fromscene_Test fromscene_test = 101;
  if (_internal_has_fromscene_test()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(101, _Internal::fromscene_test(this),
        _Internal::fromscene_test(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inner.InnerFamilysvr)
  return target;
}

size_t InnerFamilysvr::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inner.InnerFamilysvr)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 fromuser = 1;
  if (this->_internal_fromuser() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_fromuser());
  }

  switch (Fromscene_case()) {
    // .inner.InnerFamilysvr_Fromscene_Test fromscene_test = 101;
    case kFromsceneTest: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *Fromscene_.fromscene_test_);
      break;
    }
    case FROMSCENE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerFamilysvr::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerFamilysvr::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerFamilysvr::GetClassData() const { return &_class_data_; }

void InnerFamilysvr::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerFamilysvr *>(to)->MergeFrom(
      static_cast<const InnerFamilysvr &>(from));
}


void InnerFamilysvr::MergeFrom(const InnerFamilysvr& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inner.InnerFamilysvr)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_fromuser() != 0) {
    _internal_set_fromuser(from._internal_fromuser());
  }
  switch (from.Fromscene_case()) {
    case kFromsceneTest: {
      _internal_mutable_fromscene_test()->::inner::InnerFamilysvr_Fromscene_Test::MergeFrom(from._internal_fromscene_test());
      break;
    }
    case FROMSCENE_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerFamilysvr::CopyFrom(const InnerFamilysvr& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inner.InnerFamilysvr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerFamilysvr::IsInitialized() const {
  return true;
}

void InnerFamilysvr::InternalSwap(InnerFamilysvr* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(fromuser_, other->fromuser_);
  swap(Fromscene_, other->Fromscene_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerFamilysvr::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_familysvr_2eproto_getter, &descriptor_table_familysvr_2eproto_once,
      file_level_metadata_familysvr_2eproto[0]);
}

// ===================================================================

class InnerFamilysvr_Fromscene_Test::_Internal {
 public:
};

InnerFamilysvr_Fromscene_Test::InnerFamilysvr_Fromscene_Test(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:inner.InnerFamilysvr_Fromscene_Test)
}
InnerFamilysvr_Fromscene_Test::InnerFamilysvr_Fromscene_Test(const InnerFamilysvr_Fromscene_Test& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inner.InnerFamilysvr_Fromscene_Test)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerFamilysvr_Fromscene_Test::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerFamilysvr_Fromscene_Test::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata InnerFamilysvr_Fromscene_Test::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_familysvr_2eproto_getter, &descriptor_table_familysvr_2eproto_once,
      file_level_metadata_familysvr_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace inner
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::inner::InnerFamilysvr*
Arena::CreateMaybeMessage< ::inner::InnerFamilysvr >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerFamilysvr >(arena);
}
template<> PROTOBUF_NOINLINE ::inner::InnerFamilysvr_Fromscene_Test*
Arena::CreateMaybeMessage< ::inner::InnerFamilysvr_Fromscene_Test >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerFamilysvr_Fromscene_Test >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
