// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: innerauction.proto

#include "innerauction.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace inner {
PROTOBUF_CONSTEXPR InnerAuctionGoodsUp::InnerAuctionGoodsUp(
    ::_pbi::ConstantInitialized)
  : goodsid_(0u)
  , price_(0u)
  , charge_(uint64_t{0u}){}
struct InnerAuctionGoodsUpDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerAuctionGoodsUpDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerAuctionGoodsUpDefaultTypeInternal() {}
  union {
    InnerAuctionGoodsUp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerAuctionGoodsUpDefaultTypeInternal _InnerAuctionGoodsUp_default_instance_;
PROTOBUF_CONSTEXPR InnerAuctionGoodsUpRet::InnerAuctionGoodsUpRet(
    ::_pbi::ConstantInitialized)
  : goodssize_(0u){}
struct InnerAuctionGoodsUpRetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerAuctionGoodsUpRetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerAuctionGoodsUpRetDefaultTypeInternal() {}
  union {
    InnerAuctionGoodsUpRet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerAuctionGoodsUpRetDefaultTypeInternal _InnerAuctionGoodsUpRet_default_instance_;
PROTOBUF_CONSTEXPR InnerAuctionGoodsBid::InnerAuctionGoodsBid(
    ::_pbi::ConstantInitialized)
  : objectid_(uint64_t{0u}){}
struct InnerAuctionGoodsBidDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerAuctionGoodsBidDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerAuctionGoodsBidDefaultTypeInternal() {}
  union {
    InnerAuctionGoodsBid _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerAuctionGoodsBidDefaultTypeInternal _InnerAuctionGoodsBid_default_instance_;
PROTOBUF_CONSTEXPR InnerAuctionGoodsBidRet::InnerAuctionGoodsBidRet(
    ::_pbi::ConstantInitialized){}
struct InnerAuctionGoodsBidRetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerAuctionGoodsBidRetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerAuctionGoodsBidRetDefaultTypeInternal() {}
  union {
    InnerAuctionGoodsBidRet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerAuctionGoodsBidRetDefaultTypeInternal _InnerAuctionGoodsBidRet_default_instance_;
PROTOBUF_CONSTEXPR InnerAuctionOperationReq::InnerAuctionOperationReq(
    ::_pbi::ConstantInitialized)
  : seq_(uint64_t{0u})
  , _oneof_case_{}{}
struct InnerAuctionOperationReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerAuctionOperationReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerAuctionOperationReqDefaultTypeInternal() {}
  union {
    InnerAuctionOperationReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerAuctionOperationReqDefaultTypeInternal _InnerAuctionOperationReq_default_instance_;
PROTOBUF_CONSTEXPR InnerAuctionOperationRes::InnerAuctionOperationRes(
    ::_pbi::ConstantInitialized)
  : seq_(uint64_t{0u})
  , success_(false)
  , _oneof_case_{}{}
struct InnerAuctionOperationResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerAuctionOperationResDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerAuctionOperationResDefaultTypeInternal() {}
  union {
    InnerAuctionOperationRes _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerAuctionOperationResDefaultTypeInternal _InnerAuctionOperationRes_default_instance_;
PROTOBUF_CONSTEXPR InnerAuctionOperationNtf::InnerAuctionOperationNtf(
    ::_pbi::ConstantInitialized)
  : seq_(uint64_t{0u}){}
struct InnerAuctionOperationNtfDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InnerAuctionOperationNtfDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InnerAuctionOperationNtfDefaultTypeInternal() {}
  union {
    InnerAuctionOperationNtf _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InnerAuctionOperationNtfDefaultTypeInternal _InnerAuctionOperationNtf_default_instance_;
}  // namespace inner
static ::_pb::Metadata file_level_metadata_innerauction_2eproto[7];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_innerauction_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_innerauction_2eproto = nullptr;

const uint32_t TableStruct_innerauction_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsUp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsUp, goodsid_),
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsUp, price_),
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsUp, charge_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsUpRet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsUpRet, goodssize_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsBid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsBid, objectid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionGoodsBidRet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationReq, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationReq, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationReq, seq_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationReq, op_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationRes, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationRes, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationRes, seq_),
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationRes, success_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationRes, op_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationNtf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inner::InnerAuctionOperationNtf, seq_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::inner::InnerAuctionGoodsUp)},
  { 9, -1, -1, sizeof(::inner::InnerAuctionGoodsUpRet)},
  { 16, -1, -1, sizeof(::inner::InnerAuctionGoodsBid)},
  { 23, -1, -1, sizeof(::inner::InnerAuctionGoodsBidRet)},
  { 29, -1, -1, sizeof(::inner::InnerAuctionOperationReq)},
  { 39, -1, -1, sizeof(::inner::InnerAuctionOperationRes)},
  { 50, -1, -1, sizeof(::inner::InnerAuctionOperationNtf)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::inner::_InnerAuctionGoodsUp_default_instance_._instance,
  &::inner::_InnerAuctionGoodsUpRet_default_instance_._instance,
  &::inner::_InnerAuctionGoodsBid_default_instance_._instance,
  &::inner::_InnerAuctionGoodsBidRet_default_instance_._instance,
  &::inner::_InnerAuctionOperationReq_default_instance_._instance,
  &::inner::_InnerAuctionOperationRes_default_instance_._instance,
  &::inner::_InnerAuctionOperationNtf_default_instance_._instance,
};

const char descriptor_table_protodef_innerauction_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022innerauction.proto\022\005inner\"E\n\023InnerAuct"
  "ionGoodsUp\022\017\n\007goodsId\030\001 \001(\r\022\r\n\005price\030\002 \001"
  "(\r\022\016\n\006charge\030\005 \001(\004\"+\n\026InnerAuctionGoodsU"
  "pRet\022\021\n\tgoodsSize\030\001 \001(\r\"(\n\024InnerAuctionG"
  "oodsBid\022\020\n\010objectId\030\001 \001(\004\"\031\n\027InnerAuctio"
  "nGoodsBidRet\"\215\001\n\030InnerAuctionOperationRe"
  "q\022\013\n\003seq\030\001 \001(\004\022-\n\007goodsup\030\n \001(\0132\032.inner."
  "InnerAuctionGoodsUpH\000\022/\n\010goodsbid\030\013 \001(\0132"
  "\033.inner.InnerAuctionGoodsBidH\000B\004\n\002op\"\244\001\n"
  "\030InnerAuctionOperationRes\022\013\n\003seq\030\001 \001(\004\022\017"
  "\n\007success\030\002 \001(\010\0220\n\007goodsup\030\n \001(\0132\035.inner"
  ".InnerAuctionGoodsUpRetH\000\0222\n\010goodsbid\030\013 "
  "\001(\0132\036.inner.InnerAuctionGoodsBidRetH\000B\004\n"
  "\002op\"\'\n\030InnerAuctionOperationNtf\022\013\n\003seq\030\001"
  " \001(\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_innerauction_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_innerauction_2eproto = {
    false, false, 572, descriptor_table_protodef_innerauction_2eproto,
    "innerauction.proto",
    &descriptor_table_innerauction_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_innerauction_2eproto::offsets,
    file_level_metadata_innerauction_2eproto, file_level_enum_descriptors_innerauction_2eproto,
    file_level_service_descriptors_innerauction_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_innerauction_2eproto_getter() {
  return &descriptor_table_innerauction_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_innerauction_2eproto(&descriptor_table_innerauction_2eproto);
namespace inner {

// ===================================================================

class InnerAuctionGoodsUp::_Internal {
 public:
};

InnerAuctionGoodsUp::InnerAuctionGoodsUp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:inner.InnerAuctionGoodsUp)
}
InnerAuctionGoodsUp::InnerAuctionGoodsUp(const InnerAuctionGoodsUp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&goodsid_, &from.goodsid_,
    static_cast<size_t>(reinterpret_cast<char*>(&charge_) -
    reinterpret_cast<char*>(&goodsid_)) + sizeof(charge_));
  // @@protoc_insertion_point(copy_constructor:inner.InnerAuctionGoodsUp)
}

inline void InnerAuctionGoodsUp::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&goodsid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&charge_) -
    reinterpret_cast<char*>(&goodsid_)) + sizeof(charge_));
}

InnerAuctionGoodsUp::~InnerAuctionGoodsUp() {
  // @@protoc_insertion_point(destructor:inner.InnerAuctionGoodsUp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InnerAuctionGoodsUp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InnerAuctionGoodsUp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerAuctionGoodsUp::Clear() {
// @@protoc_insertion_point(message_clear_start:inner.InnerAuctionGoodsUp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&goodsid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&charge_) -
      reinterpret_cast<char*>(&goodsid_)) + sizeof(charge_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerAuctionGoodsUp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 goodsId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          goodsid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 price = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          price_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 charge = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          charge_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerAuctionGoodsUp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inner.InnerAuctionGoodsUp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 goodsId = 1;
  if (this->_internal_goodsid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_goodsid(), target);
  }

  // uint32 price = 2;
  if (this->_internal_price() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_price(), target);
  }

  // uint64 charge = 5;
  if (this->_internal_charge() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_charge(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inner.InnerAuctionGoodsUp)
  return target;
}

size_t InnerAuctionGoodsUp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inner.InnerAuctionGoodsUp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 goodsId = 1;
  if (this->_internal_goodsid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_goodsid());
  }

  // uint32 price = 2;
  if (this->_internal_price() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_price());
  }

  // uint64 charge = 5;
  if (this->_internal_charge() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_charge());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerAuctionGoodsUp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerAuctionGoodsUp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerAuctionGoodsUp::GetClassData() const { return &_class_data_; }

void InnerAuctionGoodsUp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerAuctionGoodsUp *>(to)->MergeFrom(
      static_cast<const InnerAuctionGoodsUp &>(from));
}


void InnerAuctionGoodsUp::MergeFrom(const InnerAuctionGoodsUp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inner.InnerAuctionGoodsUp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_goodsid() != 0) {
    _internal_set_goodsid(from._internal_goodsid());
  }
  if (from._internal_price() != 0) {
    _internal_set_price(from._internal_price());
  }
  if (from._internal_charge() != 0) {
    _internal_set_charge(from._internal_charge());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerAuctionGoodsUp::CopyFrom(const InnerAuctionGoodsUp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inner.InnerAuctionGoodsUp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerAuctionGoodsUp::IsInitialized() const {
  return true;
}

void InnerAuctionGoodsUp::InternalSwap(InnerAuctionGoodsUp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InnerAuctionGoodsUp, charge_)
      + sizeof(InnerAuctionGoodsUp::charge_)
      - PROTOBUF_FIELD_OFFSET(InnerAuctionGoodsUp, goodsid_)>(
          reinterpret_cast<char*>(&goodsid_),
          reinterpret_cast<char*>(&other->goodsid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerAuctionGoodsUp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_innerauction_2eproto_getter, &descriptor_table_innerauction_2eproto_once,
      file_level_metadata_innerauction_2eproto[0]);
}

// ===================================================================

class InnerAuctionGoodsUpRet::_Internal {
 public:
};

InnerAuctionGoodsUpRet::InnerAuctionGoodsUpRet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:inner.InnerAuctionGoodsUpRet)
}
InnerAuctionGoodsUpRet::InnerAuctionGoodsUpRet(const InnerAuctionGoodsUpRet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  goodssize_ = from.goodssize_;
  // @@protoc_insertion_point(copy_constructor:inner.InnerAuctionGoodsUpRet)
}

inline void InnerAuctionGoodsUpRet::SharedCtor() {
goodssize_ = 0u;
}

InnerAuctionGoodsUpRet::~InnerAuctionGoodsUpRet() {
  // @@protoc_insertion_point(destructor:inner.InnerAuctionGoodsUpRet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InnerAuctionGoodsUpRet::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InnerAuctionGoodsUpRet::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerAuctionGoodsUpRet::Clear() {
// @@protoc_insertion_point(message_clear_start:inner.InnerAuctionGoodsUpRet)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  goodssize_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerAuctionGoodsUpRet::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 goodsSize = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          goodssize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerAuctionGoodsUpRet::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inner.InnerAuctionGoodsUpRet)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 goodsSize = 1;
  if (this->_internal_goodssize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_goodssize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inner.InnerAuctionGoodsUpRet)
  return target;
}

size_t InnerAuctionGoodsUpRet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inner.InnerAuctionGoodsUpRet)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 goodsSize = 1;
  if (this->_internal_goodssize() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_goodssize());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerAuctionGoodsUpRet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerAuctionGoodsUpRet::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerAuctionGoodsUpRet::GetClassData() const { return &_class_data_; }

void InnerAuctionGoodsUpRet::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerAuctionGoodsUpRet *>(to)->MergeFrom(
      static_cast<const InnerAuctionGoodsUpRet &>(from));
}


void InnerAuctionGoodsUpRet::MergeFrom(const InnerAuctionGoodsUpRet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inner.InnerAuctionGoodsUpRet)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_goodssize() != 0) {
    _internal_set_goodssize(from._internal_goodssize());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerAuctionGoodsUpRet::CopyFrom(const InnerAuctionGoodsUpRet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inner.InnerAuctionGoodsUpRet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerAuctionGoodsUpRet::IsInitialized() const {
  return true;
}

void InnerAuctionGoodsUpRet::InternalSwap(InnerAuctionGoodsUpRet* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(goodssize_, other->goodssize_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerAuctionGoodsUpRet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_innerauction_2eproto_getter, &descriptor_table_innerauction_2eproto_once,
      file_level_metadata_innerauction_2eproto[1]);
}

// ===================================================================

class InnerAuctionGoodsBid::_Internal {
 public:
};

InnerAuctionGoodsBid::InnerAuctionGoodsBid(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:inner.InnerAuctionGoodsBid)
}
InnerAuctionGoodsBid::InnerAuctionGoodsBid(const InnerAuctionGoodsBid& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  objectid_ = from.objectid_;
  // @@protoc_insertion_point(copy_constructor:inner.InnerAuctionGoodsBid)
}

inline void InnerAuctionGoodsBid::SharedCtor() {
objectid_ = uint64_t{0u};
}

InnerAuctionGoodsBid::~InnerAuctionGoodsBid() {
  // @@protoc_insertion_point(destructor:inner.InnerAuctionGoodsBid)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InnerAuctionGoodsBid::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InnerAuctionGoodsBid::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerAuctionGoodsBid::Clear() {
// @@protoc_insertion_point(message_clear_start:inner.InnerAuctionGoodsBid)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  objectid_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerAuctionGoodsBid::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 objectId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          objectid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerAuctionGoodsBid::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inner.InnerAuctionGoodsBid)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_objectid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inner.InnerAuctionGoodsBid)
  return target;
}

size_t InnerAuctionGoodsBid::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inner.InnerAuctionGoodsBid)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_objectid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerAuctionGoodsBid::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerAuctionGoodsBid::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerAuctionGoodsBid::GetClassData() const { return &_class_data_; }

void InnerAuctionGoodsBid::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerAuctionGoodsBid *>(to)->MergeFrom(
      static_cast<const InnerAuctionGoodsBid &>(from));
}


void InnerAuctionGoodsBid::MergeFrom(const InnerAuctionGoodsBid& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inner.InnerAuctionGoodsBid)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_objectid() != 0) {
    _internal_set_objectid(from._internal_objectid());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerAuctionGoodsBid::CopyFrom(const InnerAuctionGoodsBid& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inner.InnerAuctionGoodsBid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerAuctionGoodsBid::IsInitialized() const {
  return true;
}

void InnerAuctionGoodsBid::InternalSwap(InnerAuctionGoodsBid* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(objectid_, other->objectid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerAuctionGoodsBid::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_innerauction_2eproto_getter, &descriptor_table_innerauction_2eproto_once,
      file_level_metadata_innerauction_2eproto[2]);
}

// ===================================================================

class InnerAuctionGoodsBidRet::_Internal {
 public:
};

InnerAuctionGoodsBidRet::InnerAuctionGoodsBidRet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:inner.InnerAuctionGoodsBidRet)
}
InnerAuctionGoodsBidRet::InnerAuctionGoodsBidRet(const InnerAuctionGoodsBidRet& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inner.InnerAuctionGoodsBidRet)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerAuctionGoodsBidRet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerAuctionGoodsBidRet::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata InnerAuctionGoodsBidRet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_innerauction_2eproto_getter, &descriptor_table_innerauction_2eproto_once,
      file_level_metadata_innerauction_2eproto[3]);
}

// ===================================================================

class InnerAuctionOperationReq::_Internal {
 public:
  static const ::inner::InnerAuctionGoodsUp& goodsup(const InnerAuctionOperationReq* msg);
  static const ::inner::InnerAuctionGoodsBid& goodsbid(const InnerAuctionOperationReq* msg);
};

const ::inner::InnerAuctionGoodsUp&
InnerAuctionOperationReq::_Internal::goodsup(const InnerAuctionOperationReq* msg) {
  return *msg->op_.goodsup_;
}
const ::inner::InnerAuctionGoodsBid&
InnerAuctionOperationReq::_Internal::goodsbid(const InnerAuctionOperationReq* msg) {
  return *msg->op_.goodsbid_;
}
void InnerAuctionOperationReq::set_allocated_goodsup(::inner::InnerAuctionGoodsUp* goodsup) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_op();
  if (goodsup) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(goodsup);
    if (message_arena != submessage_arena) {
      goodsup = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, goodsup, submessage_arena);
    }
    set_has_goodsup();
    op_.goodsup_ = goodsup;
  }
  // @@protoc_insertion_point(field_set_allocated:inner.InnerAuctionOperationReq.goodsup)
}
void InnerAuctionOperationReq::set_allocated_goodsbid(::inner::InnerAuctionGoodsBid* goodsbid) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_op();
  if (goodsbid) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(goodsbid);
    if (message_arena != submessage_arena) {
      goodsbid = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, goodsbid, submessage_arena);
    }
    set_has_goodsbid();
    op_.goodsbid_ = goodsbid;
  }
  // @@protoc_insertion_point(field_set_allocated:inner.InnerAuctionOperationReq.goodsbid)
}
InnerAuctionOperationReq::InnerAuctionOperationReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:inner.InnerAuctionOperationReq)
}
InnerAuctionOperationReq::InnerAuctionOperationReq(const InnerAuctionOperationReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  seq_ = from.seq_;
  clear_has_op();
  switch (from.op_case()) {
    case kGoodsup: {
      _internal_mutable_goodsup()->::inner::InnerAuctionGoodsUp::MergeFrom(from._internal_goodsup());
      break;
    }
    case kGoodsbid: {
      _internal_mutable_goodsbid()->::inner::InnerAuctionGoodsBid::MergeFrom(from._internal_goodsbid());
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:inner.InnerAuctionOperationReq)
}

inline void InnerAuctionOperationReq::SharedCtor() {
seq_ = uint64_t{0u};
clear_has_op();
}

InnerAuctionOperationReq::~InnerAuctionOperationReq() {
  // @@protoc_insertion_point(destructor:inner.InnerAuctionOperationReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InnerAuctionOperationReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_op()) {
    clear_op();
  }
}

void InnerAuctionOperationReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerAuctionOperationReq::clear_op() {
// @@protoc_insertion_point(one_of_clear_start:inner.InnerAuctionOperationReq)
  switch (op_case()) {
    case kGoodsup: {
      if (GetArenaForAllocation() == nullptr) {
        delete op_.goodsup_;
      }
      break;
    }
    case kGoodsbid: {
      if (GetArenaForAllocation() == nullptr) {
        delete op_.goodsbid_;
      }
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = OP_NOT_SET;
}


void InnerAuctionOperationReq::Clear() {
// @@protoc_insertion_point(message_clear_start:inner.InnerAuctionOperationReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  seq_ = uint64_t{0u};
  clear_op();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerAuctionOperationReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 seq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          seq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .inner.InnerAuctionGoodsUp goodsup = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_goodsup(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .inner.InnerAuctionGoodsBid goodsbid = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_goodsbid(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerAuctionOperationReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inner.InnerAuctionOperationReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 seq = 1;
  if (this->_internal_seq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_seq(), target);
  }

  // .inner.InnerAuctionGoodsUp goodsup = 10;
  if (_internal_has_goodsup()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::goodsup(this),
        _Internal::goodsup(this).GetCachedSize(), target, stream);
  }

  // .inner.InnerAuctionGoodsBid goodsbid = 11;
  if (_internal_has_goodsbid()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::goodsbid(this),
        _Internal::goodsbid(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inner.InnerAuctionOperationReq)
  return target;
}

size_t InnerAuctionOperationReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inner.InnerAuctionOperationReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 seq = 1;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_seq());
  }

  switch (op_case()) {
    // .inner.InnerAuctionGoodsUp goodsup = 10;
    case kGoodsup: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *op_.goodsup_);
      break;
    }
    // .inner.InnerAuctionGoodsBid goodsbid = 11;
    case kGoodsbid: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *op_.goodsbid_);
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerAuctionOperationReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerAuctionOperationReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerAuctionOperationReq::GetClassData() const { return &_class_data_; }

void InnerAuctionOperationReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerAuctionOperationReq *>(to)->MergeFrom(
      static_cast<const InnerAuctionOperationReq &>(from));
}


void InnerAuctionOperationReq::MergeFrom(const InnerAuctionOperationReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inner.InnerAuctionOperationReq)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_seq() != 0) {
    _internal_set_seq(from._internal_seq());
  }
  switch (from.op_case()) {
    case kGoodsup: {
      _internal_mutable_goodsup()->::inner::InnerAuctionGoodsUp::MergeFrom(from._internal_goodsup());
      break;
    }
    case kGoodsbid: {
      _internal_mutable_goodsbid()->::inner::InnerAuctionGoodsBid::MergeFrom(from._internal_goodsbid());
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerAuctionOperationReq::CopyFrom(const InnerAuctionOperationReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inner.InnerAuctionOperationReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerAuctionOperationReq::IsInitialized() const {
  return true;
}

void InnerAuctionOperationReq::InternalSwap(InnerAuctionOperationReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(seq_, other->seq_);
  swap(op_, other->op_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerAuctionOperationReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_innerauction_2eproto_getter, &descriptor_table_innerauction_2eproto_once,
      file_level_metadata_innerauction_2eproto[4]);
}

// ===================================================================

class InnerAuctionOperationRes::_Internal {
 public:
  static const ::inner::InnerAuctionGoodsUpRet& goodsup(const InnerAuctionOperationRes* msg);
  static const ::inner::InnerAuctionGoodsBidRet& goodsbid(const InnerAuctionOperationRes* msg);
};

const ::inner::InnerAuctionGoodsUpRet&
InnerAuctionOperationRes::_Internal::goodsup(const InnerAuctionOperationRes* msg) {
  return *msg->op_.goodsup_;
}
const ::inner::InnerAuctionGoodsBidRet&
InnerAuctionOperationRes::_Internal::goodsbid(const InnerAuctionOperationRes* msg) {
  return *msg->op_.goodsbid_;
}
void InnerAuctionOperationRes::set_allocated_goodsup(::inner::InnerAuctionGoodsUpRet* goodsup) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_op();
  if (goodsup) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(goodsup);
    if (message_arena != submessage_arena) {
      goodsup = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, goodsup, submessage_arena);
    }
    set_has_goodsup();
    op_.goodsup_ = goodsup;
  }
  // @@protoc_insertion_point(field_set_allocated:inner.InnerAuctionOperationRes.goodsup)
}
void InnerAuctionOperationRes::set_allocated_goodsbid(::inner::InnerAuctionGoodsBidRet* goodsbid) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_op();
  if (goodsbid) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(goodsbid);
    if (message_arena != submessage_arena) {
      goodsbid = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, goodsbid, submessage_arena);
    }
    set_has_goodsbid();
    op_.goodsbid_ = goodsbid;
  }
  // @@protoc_insertion_point(field_set_allocated:inner.InnerAuctionOperationRes.goodsbid)
}
InnerAuctionOperationRes::InnerAuctionOperationRes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:inner.InnerAuctionOperationRes)
}
InnerAuctionOperationRes::InnerAuctionOperationRes(const InnerAuctionOperationRes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&seq_, &from.seq_,
    static_cast<size_t>(reinterpret_cast<char*>(&success_) -
    reinterpret_cast<char*>(&seq_)) + sizeof(success_));
  clear_has_op();
  switch (from.op_case()) {
    case kGoodsup: {
      _internal_mutable_goodsup()->::inner::InnerAuctionGoodsUpRet::MergeFrom(from._internal_goodsup());
      break;
    }
    case kGoodsbid: {
      _internal_mutable_goodsbid()->::inner::InnerAuctionGoodsBidRet::MergeFrom(from._internal_goodsbid());
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:inner.InnerAuctionOperationRes)
}

inline void InnerAuctionOperationRes::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&seq_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&success_) -
    reinterpret_cast<char*>(&seq_)) + sizeof(success_));
clear_has_op();
}

InnerAuctionOperationRes::~InnerAuctionOperationRes() {
  // @@protoc_insertion_point(destructor:inner.InnerAuctionOperationRes)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InnerAuctionOperationRes::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_op()) {
    clear_op();
  }
}

void InnerAuctionOperationRes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerAuctionOperationRes::clear_op() {
// @@protoc_insertion_point(one_of_clear_start:inner.InnerAuctionOperationRes)
  switch (op_case()) {
    case kGoodsup: {
      if (GetArenaForAllocation() == nullptr) {
        delete op_.goodsup_;
      }
      break;
    }
    case kGoodsbid: {
      if (GetArenaForAllocation() == nullptr) {
        delete op_.goodsbid_;
      }
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = OP_NOT_SET;
}


void InnerAuctionOperationRes::Clear() {
// @@protoc_insertion_point(message_clear_start:inner.InnerAuctionOperationRes)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&seq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&success_) -
      reinterpret_cast<char*>(&seq_)) + sizeof(success_));
  clear_op();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerAuctionOperationRes::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 seq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          seq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool success = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .inner.InnerAuctionGoodsUpRet goodsup = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_goodsup(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .inner.InnerAuctionGoodsBidRet goodsbid = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_goodsbid(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerAuctionOperationRes::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inner.InnerAuctionOperationRes)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 seq = 1;
  if (this->_internal_seq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_seq(), target);
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_success(), target);
  }

  // .inner.InnerAuctionGoodsUpRet goodsup = 10;
  if (_internal_has_goodsup()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::goodsup(this),
        _Internal::goodsup(this).GetCachedSize(), target, stream);
  }

  // .inner.InnerAuctionGoodsBidRet goodsbid = 11;
  if (_internal_has_goodsbid()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::goodsbid(this),
        _Internal::goodsbid(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inner.InnerAuctionOperationRes)
  return target;
}

size_t InnerAuctionOperationRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inner.InnerAuctionOperationRes)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 seq = 1;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_seq());
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  switch (op_case()) {
    // .inner.InnerAuctionGoodsUpRet goodsup = 10;
    case kGoodsup: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *op_.goodsup_);
      break;
    }
    // .inner.InnerAuctionGoodsBidRet goodsbid = 11;
    case kGoodsbid: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *op_.goodsbid_);
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerAuctionOperationRes::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerAuctionOperationRes::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerAuctionOperationRes::GetClassData() const { return &_class_data_; }

void InnerAuctionOperationRes::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerAuctionOperationRes *>(to)->MergeFrom(
      static_cast<const InnerAuctionOperationRes &>(from));
}


void InnerAuctionOperationRes::MergeFrom(const InnerAuctionOperationRes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inner.InnerAuctionOperationRes)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_seq() != 0) {
    _internal_set_seq(from._internal_seq());
  }
  if (from._internal_success() != 0) {
    _internal_set_success(from._internal_success());
  }
  switch (from.op_case()) {
    case kGoodsup: {
      _internal_mutable_goodsup()->::inner::InnerAuctionGoodsUpRet::MergeFrom(from._internal_goodsup());
      break;
    }
    case kGoodsbid: {
      _internal_mutable_goodsbid()->::inner::InnerAuctionGoodsBidRet::MergeFrom(from._internal_goodsbid());
      break;
    }
    case OP_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerAuctionOperationRes::CopyFrom(const InnerAuctionOperationRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inner.InnerAuctionOperationRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerAuctionOperationRes::IsInitialized() const {
  return true;
}

void InnerAuctionOperationRes::InternalSwap(InnerAuctionOperationRes* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InnerAuctionOperationRes, success_)
      + sizeof(InnerAuctionOperationRes::success_)
      - PROTOBUF_FIELD_OFFSET(InnerAuctionOperationRes, seq_)>(
          reinterpret_cast<char*>(&seq_),
          reinterpret_cast<char*>(&other->seq_));
  swap(op_, other->op_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerAuctionOperationRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_innerauction_2eproto_getter, &descriptor_table_innerauction_2eproto_once,
      file_level_metadata_innerauction_2eproto[5]);
}

// ===================================================================

class InnerAuctionOperationNtf::_Internal {
 public:
};

InnerAuctionOperationNtf::InnerAuctionOperationNtf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:inner.InnerAuctionOperationNtf)
}
InnerAuctionOperationNtf::InnerAuctionOperationNtf(const InnerAuctionOperationNtf& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  seq_ = from.seq_;
  // @@protoc_insertion_point(copy_constructor:inner.InnerAuctionOperationNtf)
}

inline void InnerAuctionOperationNtf::SharedCtor() {
seq_ = uint64_t{0u};
}

InnerAuctionOperationNtf::~InnerAuctionOperationNtf() {
  // @@protoc_insertion_point(destructor:inner.InnerAuctionOperationNtf)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InnerAuctionOperationNtf::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InnerAuctionOperationNtf::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerAuctionOperationNtf::Clear() {
// @@protoc_insertion_point(message_clear_start:inner.InnerAuctionOperationNtf)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  seq_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerAuctionOperationNtf::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 seq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          seq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerAuctionOperationNtf::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inner.InnerAuctionOperationNtf)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 seq = 1;
  if (this->_internal_seq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_seq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inner.InnerAuctionOperationNtf)
  return target;
}

size_t InnerAuctionOperationNtf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inner.InnerAuctionOperationNtf)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 seq = 1;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_seq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerAuctionOperationNtf::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerAuctionOperationNtf::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerAuctionOperationNtf::GetClassData() const { return &_class_data_; }

void InnerAuctionOperationNtf::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerAuctionOperationNtf *>(to)->MergeFrom(
      static_cast<const InnerAuctionOperationNtf &>(from));
}


void InnerAuctionOperationNtf::MergeFrom(const InnerAuctionOperationNtf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inner.InnerAuctionOperationNtf)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_seq() != 0) {
    _internal_set_seq(from._internal_seq());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerAuctionOperationNtf::CopyFrom(const InnerAuctionOperationNtf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inner.InnerAuctionOperationNtf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerAuctionOperationNtf::IsInitialized() const {
  return true;
}

void InnerAuctionOperationNtf::InternalSwap(InnerAuctionOperationNtf* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(seq_, other->seq_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerAuctionOperationNtf::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_innerauction_2eproto_getter, &descriptor_table_innerauction_2eproto_once,
      file_level_metadata_innerauction_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace inner
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::inner::InnerAuctionGoodsUp*
Arena::CreateMaybeMessage< ::inner::InnerAuctionGoodsUp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerAuctionGoodsUp >(arena);
}
template<> PROTOBUF_NOINLINE ::inner::InnerAuctionGoodsUpRet*
Arena::CreateMaybeMessage< ::inner::InnerAuctionGoodsUpRet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerAuctionGoodsUpRet >(arena);
}
template<> PROTOBUF_NOINLINE ::inner::InnerAuctionGoodsBid*
Arena::CreateMaybeMessage< ::inner::InnerAuctionGoodsBid >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerAuctionGoodsBid >(arena);
}
template<> PROTOBUF_NOINLINE ::inner::InnerAuctionGoodsBidRet*
Arena::CreateMaybeMessage< ::inner::InnerAuctionGoodsBidRet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerAuctionGoodsBidRet >(arena);
}
template<> PROTOBUF_NOINLINE ::inner::InnerAuctionOperationReq*
Arena::CreateMaybeMessage< ::inner::InnerAuctionOperationReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerAuctionOperationReq >(arena);
}
template<> PROTOBUF_NOINLINE ::inner::InnerAuctionOperationRes*
Arena::CreateMaybeMessage< ::inner::InnerAuctionOperationRes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerAuctionOperationRes >(arena);
}
template<> PROTOBUF_NOINLINE ::inner::InnerAuctionOperationNtf*
Arena::CreateMaybeMessage< ::inner::InnerAuctionOperationNtf >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inner::InnerAuctionOperationNtf >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
